var name = "Aman Singh";
var school = "IFTM University";
var course = "BCA";
var rollno = 101;
var ds = 67;
var de = 78;
var java = 88;
var total = ds+de+java;
var per = total/3;
console.log("----------------------------------");
console.log("| Name : "+name);
console.log("| School : "+school);
console.log("| Course : "+course);
console.log("| Roll No : "+rollno);
console.log("| Data Structure : "+ds);
console.log("| Digital Electronic : "+de);
console.log("| Java : "+java);
console.log("| Total : "+total);
console.log("| Percentage : "+per);
console.log("----------------------------------");